### ISSUE TITLE
Cljc changes doesn't seem to get reported

### ISSUE THREAD

**Issue by jaen** [weavejester/ns-tracker#20]
Hello, I'm using `system.boot` which uses `ns-tracker.core/ns-tracker` to track file changes ([relevant code](https://github.com/danielsz/system/blob/master/src/system/boot.clj#L21)).
For some reason it sees changes in `clj` files, but for `cljc` calling the ns tracker returns an empty seq. `tools.namespace`, at least from the readme, seem to support `cljc` files. Is that not the case for `ns-tracker`?

**Comment by weavejester** [comment]
Apologies for the late response. The current version of ns-tracker predates Clojure 1.7 files, so it may very well not work with cljc files. It certainly hasn't been tested with them.

Since ns-tracker was written, a lot of additional code has been added to tools.namespace, and I suspect a lot of code in ns-tracker itself is now unnecessary. Let me see what I can do.

**Comment by weavejester** [comment]
What happens if you update your `tools.namespace` dependency to `"0.2.11"`. Does that fix the problem?

**Comment by jaen** [comment]
@weavejester seems updating the dependency as suggested fixes it. Thanks a lot!

**Comment by Deraen** [comment]
This causes problems with boot-cljs which is using ns-tracker to reload macro namespaces. Currently ns-tracker doesn't notice changes in namespaces which use reader conditionals in `ns` form. I have a report that updating the tools.namespace dependency fixes this: https://github.com/adzerk-oss/boot-cljs/issues/121#issuecomment-192565828

I could force boot-cljs to use latest tools.namespace, but would be even better to have ns-tracker updated to use latest tools.namespace.
